export interface DocSpringTemplate {
      expiration_interval: string,
      webhook_url: null|string,
      parent_folder_id: null|string,
      expire_after: number,
      allow_additional_properties: boolean,
      description: null|string,
      public_submissions: boolean,
      slack_webhook_url: null|string,
      path: string,
      public_web_form: boolean,
      editable_submissions: boolean,
      expire_submissions: boolean,
      name: string,
      permanent_document_url: string,
      template_type: string,
      id: string, 
      page_dimensions: null|Array<number>,
      locked: boolean,
      redirect_url: null|string,
      document_url: string,
    }