export const predefined_fields_sample_data = {
  first_name: 'John',
  last_name: 'Doe',
  user_email: 'john.doe@example.com',
  user_website: 'https://www.example.com',
  user_phone: '123-456-7890',
  dob: '1990-01-01',
  signup_date: '2021-01-01',
  age: 33,
  is_active: true,
  user_address: {
    address_line_1: '123 Main St',
    address_line_2: 'Apt 4B',
    city: 'Springfield',
    state: 'IL',
    zip: '62701',
    country: 'USA',
  },
  subscription_plan: 'premium',
  last_login: '2021-01-01T00:00:00',
  is_verified: true,
  preferences: {
    theme: 'dark',
    language: 'en',
  },
  user_roles: ['admin', 'editor'],
}

export const predefined_fields_example = [
  {
    name: 'first_name',
    type: 'string',
    required: true,
  },
  {
    name: 'last_name',
    type: 'string',
    required: true,
  },
  {
    name: 'user_email',
    type: 'email',
    required: true,
  },
  {
    name: 'user_website',
    type: 'url',
    required: true,
  },
  {
    name: 'user_phone',
    type: 'phone',
    required: true,
  },
  {
    name: 'dob',
    type: 'date',
    required: true,
  },
  {
    name: 'signup_date',
    type: 'date',
    required: true,
  },
  {
    name: 'age',
    type: 'number',
    required: true,
  },
  {
    name: 'is_active',
    type: 'boolean',
    required: true,
  },
  {
    name: 'user_address/address_line_1',
    type: 'address',
    required: true,
  },
  {
    name: 'user_address/address_line_2',
    type: 'string',
    required: false,
  },
  {
    name: 'user_address/city',
    type: 'string',
    required: true,
  },
  {
    name: 'user_address/state',
    type: 'string',
    required: true,
  },
  {
    name: 'user_address/zip',
    type: 'string',
    required: true,
  },
  {
    name: 'user_address/country',
    type: 'string',
    required: true,
  },
  {
    name: 'subscription_plan',
    type: 'string',
    required: false,
  },
  {
    name: 'last_login',
    type: 'datetime',
    required: false,
  },
  {
    name: 'is_verified',
    type: 'boolean',
    required: true,
  },
  {
    name: 'preferences/theme',
    type: 'string',
    required: false,
  },
  {
    name: 'preferences/language',
    type: 'string',
    required: true,
  },
  {
    name: 'user_roles/0',
    type: 'string',
    required: true,
  },
  {
    name: 'user_roles/1',
    type: 'string',
    required: true,
  },
  {
    name: 'user_roles/2',
    type: 'string',
    required: false,
  },
  {
    name: 'user_roles/3',
    type: 'string',
    required: false,
  },
]

export const fw_8ben_sample_data = {
  full_name: 'John Doe',
  country_of_citizenship: 'United Kingdom',
  permanent_residence_address: {
    street: '123 Main St',
    city: 'London',
    zip: 'SW1A 1AA',
    country: 'UK',
  },
  mailing_address: '456 Secondary St, London, UK',
  us_taxpayer_identification_number: '123-45-6789',
  foreign_tax_identifying_number: 'UK1234567',
  date_of_birth: '1990-01-01',
  reference_number: 'REF123',
  chapter_3_status: 'Individual',
  chapter_4_status: 'Individual',
  claim_of_tax_treaty_benefits: true,
  special_rates_and_conditions: 'Article 12',
  explanation_attached: false,
  signature: 'signature_data',
  capacity_in_which_acting: 'Individual',
  date_signed: '2023-01-01',
  substitute_form: false,
  witness_signature: 'witness_signature_data',
  witness_date_signed: '2023-01-02',
  witness_capacity_in_which_acting: 'Witness',
}

export const fw_8ben_predefined_fields = [
  { name: 'full_name', type: 'string', required: true },
  { name: 'country_of_citizenship', type: 'country', required: true },
  {
    name: 'permanent_residence_address/street',
    type: 'string',
    required: true,
  },
  { name: 'permanent_residence_address/city', type: 'string', required: true },
  { name: 'permanent_residence_address/zip', type: 'string', required: true },
  {
    name: 'permanent_residence_address/country',
    type: 'country',
    required: true,
  },
  { name: 'mailing_address', type: 'string', required: false },
  {
    name: 'us_taxpayer_identification_number',
    type: 'string',
    required: false,
  },
  { name: 'foreign_tax_identifying_number', type: 'string', required: true },
  { name: 'date_of_birth', type: 'date', required: true },
  { name: 'reference_number', type: 'string', required: false },
  { name: 'chapter_3_status', type: 'string', required: true },
  { name: 'chapter_4_status', type: 'string', required: true },
  { name: 'claim_of_tax_treaty_benefits', type: 'boolean', required: true },
  { name: 'special_rates_and_conditions', type: 'string', required: false },
  { name: 'explanation_attached', type: 'boolean', required: false },
  { name: 'signature', type: 'signature', required: true },
  { name: 'capacity_in_which_acting', type: 'string', required: false },
  { name: 'date_signed', type: 'date', required: true },
  { name: 'substitute_form', type: 'boolean', required: false },
  { name: 'witness_signature', type: 'signature', required: false },
  { name: 'witness_date_signed', type: 'date', required: false },
  { name: 'witness_capacity_in_which_acting', type: 'string', required: false },
]
